apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r82dvjkbw-nodejs 
  janus-idp.io/tekton: r82dvjkbw-nodejs
  backstage.io/kubernetes-id: r82dvjkbw-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r82dvjkbw-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml